ALTER TABLE roles
    ADD COLUMN IF NOT EXISTS updated_by BIGINT,
    ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE roles
    ADD COLUMN IF NOT EXISTS created_by BIGINT;

UPDATE roles
SET created_by = 1
WHERE created_by IS NULL;

ALTER TABLE roles
    ALTER COLUMN created_by SET NOT NULL;